# Copyright (c) 2023-2024, Arm Limited.
#
# SPDX-License-Identifier: Apache-2.0

.PHONY: all
all:
	@$(MAKE) -C wrk2-aarch64 all

.PHONY: help
help:
	@echo "Make Targets:"
	@echo " all        - Build traffic generator tools"
